#!/usr/bin/env bash

input="$HOME/.cache/wal/colors.json"
output="$HOME/.cache/wal/dynacat/colors-dynacat.yaml"
output_dir="$(dirname "$output")"

if [[ ! -d "$output_dir" ]]; then
	echo "Creating $output_dir"
	mkdir -p "$output_dir"
fi

if ! command -v jq >/dev/null 2>&1; then
	echo "Error: jq is not installed"
	exit 1
fi
if [[ ! -r "$input" ]]; then
	echo "Error: cannot read $input"
fi

# --- hex -> "H S L" ----------------------------------------------------------
# Outputs hue (0-360), saturation (0-100), lightness (0-100), rounded.
# Bash has no floating-point math, so awk does the arithmetic.
# (Generated by claude)
hex_to_hsl() {
	local hex="${1#\#}"
	[[ "$hex" =~ ^[0-9A-Fa-f]{6}$ ]] || { echo "error: bad hex '$1'" >&2; exit 1; }

	local r g b
	r=$((16#${hex:0:2}))
	g=$((16#${hex:2:2}))
	b=$((16#${hex:4:2}))

	awk -v r="$r" -v g="$g" -v b="$b" 'BEGIN {
		r/=255; g/=255; b/=255
		max = (r>g ? (r>b?r:b) : (g>b?g:b))
		min = (r<g ? (r<b?r:b) : (g<b?g:b))
		l = (max+min)/2
		if (max == min) { h=0; s=0 }
		else {
			d = max-min
			s = (l>0.5) ? d/(2-max-min) : d/(max+min)
			if      (max==r) h = (g-b)/d + (g<b ? 6 : 0)
			else if (max==g) h = (b-r)/d + 2
			else             h = (r-g)/d + 4
				h /= 6
		}
	printf "%d %d %d", h*360+0.5, s*100+0.5, l*100+0.5
}'
}

bg_hex="$(jq -r '.special.background' "$input")"
read -r bg_h bg_s bg_l <<< "$(hex_to_hsl "$bg_hex")"
col1_hex="$(jq -r '.colors.color1' "$input")"
read -r col1_h col1_s col1_l <<< "$(hex_to_hsl "$col1_hex")"
col2_hex="$(jq -r '.colors.color2' "$input")"
read -r col2_h col2_s col2_l <<< "$(hex_to_hsl "$col2_hex")"
col6_hex="$(jq -r '.colors.color6' "$input")"
read -r col6_h col6_s col6_l <<< "$(hex_to_hsl "$col6_hex")"

cat > "$output" <<EOF
background-color: $bg_h $bg_s $bg_l
primary-color: $col6_h $col6_s $col6_l
positive-color: $col2_h $col2_s $col2_l
negative-color: $col1_h $col1_s $col1_l
contrast-multiplier: 1.1
EOF

echo "Wrote $output"
