general {
  # avoid starting multiple hyprlock instances.
  lock_cmd = pidof hyprlock || hyprlock

  # lock before suspend.
  before_sleep_cmd = loginctl lock-session

  # to avoid having to press a key twice to turn on the display.
  after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
  # 4 min
  timeout = 240
  on-timeout = notify-send -a hypridle "Screen will turn off in 1 minute! 🌚"
  on-resume = notify-send -a hypridle "Screen stays on. 🌞"
}

listener {
  # 5 min
  timeout = 300
  on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
  on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
  # 20 min
  timeout = 1200
  on-timeout = loginctl lock-session
}
